apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: srjchsv/auth-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: myapp
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
