apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: srjchsv/chat-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: chat-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: myapp
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
