apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: srjchsv/chat-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: chat-frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  namespace: myapp
spec:
  selector:
    app: chat-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP



