apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-db
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-db
  template:
    metadata:
      labels:
        app: chat-db
    spec:
      containers:
        - name: chat-db
          image: postgres:15.2-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: chat-service-config
          volumeMounts:
            - name: chat-db-data
              mountPath: /var/lib/postgresql/dat
      volumes:
        - name: chat-db-data
          persistentVolumeClaim:
            claimName: chat-db-data

---
apiVersion: v1
kind: Service
metadata:
  name: chat-db
  namespace: myapp
spec:
  selector:
    app: chat-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
