apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: myapp
data:
  PORT: "8080"
  POSTGRES_HOST: auth-db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: user
  POSTGRES_PASSWORD: auth
  POSTGRES_DB: auth
